#!/usr/bin/env bash
set -e

echo "========================================================"
echo " Meridian — AWS SAM Production Deployment"
echo "========================================================"

# 1. Check for SAM CLI
if ! command -v sam &> /dev/null; then
    echo "⚠️  AWS SAM CLI is not installed or not in PATH."
    echo "To install on macOS via Homebrew:"
    echo "  brew install aws-sam-cli"
    echo ""
    echo "Alternatively, download the official installer from:"
    echo "  https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/install-sam-cli.html"
    exit 1
fi

# 2. Check for AWS Credentials
if ! aws sts get-caller-identity &> /dev/null; then
    echo "⚠️  AWS credentials not detected."
    echo "Please configure your AWS CLI credentials first:"
    echo "  export AWS_ACCESS_KEY_ID=your_key"
    echo "  export AWS_SECRET_ACCESS_KEY=your_secret"
    echo "  export AWS_DEFAULT_REGION=us-east-1"
    echo "Or run: aws configure"
    exit 1
fi

CALLER_IDENTITY=$(aws sts get-caller-identity --output text --query 'Arn')
echo "✅ Authenticated with AWS as: $CALLER_IDENTITY"

# 3. Build SAM application
echo "Building serverless application artifacts..."
cd "$(dirname "$0")/.."
sam build

# 4. Deploy using samconfig.toml parameters
echo "Deploying CloudFormation stack: life-dashboard-backend..."
sam deploy --no-confirm-changeset

# 5. Extract CloudFormation Stack Outputs
echo "Extracting stack outputs..."
STACK_NAME="life-dashboard-backend"
REGION=$(aws configure get region || echo "us-east-1")

API_ENDPOINT=$(aws cloudformation describe-stacks --stack-name "$STACK_NAME" --region "$REGION" --query "Stacks[0].Outputs[?OutputKey=='ApiEndpoint'].OutputValue" --output text)
USER_POOL_ID=$(aws cloudformation describe-stacks --stack-name "$STACK_NAME" --region "$REGION" --query "Stacks[0].Outputs[?OutputKey=='UserPoolId'].OutputValue" --output text)
USER_POOL_CLIENT_ID=$(aws cloudformation describe-stacks --stack-name "$STACK_NAME" --region "$REGION" --query "Stacks[0].Outputs[?OutputKey=='UserPoolClientId'].OutputValue" --output text)
TABLE_NAME=$(aws cloudformation describe-stacks --stack-name "$STACK_NAME" --region "$REGION" --query "Stacks[0].Outputs[?OutputKey=='DynamoDBTableName'].OutputValue" --output text)
BUCKET_NAME=$(aws cloudformation describe-stacks --stack-name "$STACK_NAME" --region "$REGION" --query "Stacks[0].Outputs[?OutputKey=='S3BucketName'].OutputValue" --output text)
SNS_TOPIC_ARN=$(aws cloudformation describe-stacks --stack-name "$STACK_NAME" --region "$REGION" --query "Stacks[0].Outputs[?OutputKey=='SNSTopicArn'].OutputValue" --output text)

echo "--------------------------------------------------------"
echo "Deployment Succeeded!"
echo "API Gateway Endpoint: $API_ENDPOINT"
echo "Cognito User Pool ID: $USER_POOL_ID"
echo "Cognito App Client:   $USER_POOL_CLIENT_ID"
echo "DynamoDB Table:       $TABLE_NAME"
echo "S3 Storage Bucket:    $BUCKET_NAME"
echo "SNS Topic ARN:        $SNS_TOPIC_ARN"
echo "--------------------------------------------------------"

# 6. Inject into Frontend Environment Config
FRONTEND_ENV="../../frontend/.env.production"
echo "Writing environment configuration to: $FRONTEND_ENV"

cat << ENV_FILE > "$FRONTEND_ENV"
# Production AWS Configuration — Generated by SAM Deployment
VITE_API_BASE_URL=$API_ENDPOINT
VITE_COGNITO_USER_POOL_ID=$USER_POOL_ID
VITE_COGNITO_CLIENT_ID=$USER_POOL_CLIENT_ID
VITE_AWS_REGION=$REGION
ENV_FILE

echo "Frontend environment updated successfully."
echo "========================================================"
